### ISSUE TITLE
파이썬-db연동 and  db설계

### ISSUE THREAD

**Issue by idtnqls** [FunnyDain/Movie-Recommendation-System-Project#11]
웹사이트에 필요한 db와 머신러닝 구현에 필요한 전처리db를 바탕으로 ERD설계후 db 연동 해본다.

- [x] https://app.diagrams.net/ 사이트를 이용하여 ERD 설계
- [x] db 연동

**Comment by FunnyDain** [comment]
ERD를 만드시구 팀원들과 함께 회의 해봅시다!
